---
- name: provision test instances
  hosts: local
  connection: local
  vars_files:
  - ../vars/main.yml
  tasks:
    - include: keypair.yml

    - name: create the security group and rules
      nova_group:
        name: "{{ testenv_security_groups }}"
        description: "{{ testenv_instance_prefix }} {{ testenv_security_groups_description }}"
        rules:
          - ip_protocol: "{{ item.proto }}"
            from_port: "{{ item.port }}"
            to_port: "{{ item.port }}"
            cidr: 0.0.0.0/0
            state: "{{ item.state }}"
      with_items: testenv_security_group_rules
      register: testenv_security_group

    - name: create security group rules
      command: neutron security-group-rule-create --ethertype={{ item }}
               --remote-group-id={{ testenv_security_group.results[0].group_id }}
               {{ testenv_security_group.results[0].group_id }}
      register: security_group_rule_create_result
      failed_when: "security_group_rule_create_result.rc != 0 and '409' not in security_group_rule_create_result.stderr"
      changed_when: security_group_rule_create_result.rc == 0
      with_items:
      - IPv4
      - IPv6
      when: testenv_security_group.results[0].group_id

    - name: create instances
      os_server:
        name: "{{ item }}"
        image: "{{ testenv_image_id }}"
        key_name: "{{ testenv_keypair_name }}"
        security_groups: "{{ testenv_security_group.results[0].group_id }}"
        wait: yes
        timeout: 200
        flavor: 3
        nics:
          - net-name: internal
        auto_floating_ip: false
      with_items: testenv_instance_names

    - name: associate a floating IP to instances
      nova_fip: server={{ item }}
      with_items: testenv_instance_names
      register: testenv_floating_ips

    - name: wait for instances to boot
      wait_for: port=22 delay=5 timeout=600 host={{ item.floating_ip }}
      with_items: testenv_floating_ips.results
