---
- name: check if barbican user exists
  action: shell getent passwd barbican
  register: barbican_user
  failed_when: False
  changed_when: False

- name: barbican user
  user: name=barbican shell=/bin/false createhome=no
  when: barbican_user|success

- name: barbican user
  user: name=barbican comment=barbican shell=/bin/false system=yes
        home=/nonexistent createhome=no
  when: not barbican_user|success

- name: barbican config dir
  file: dest=/etc/barbican state=directory

- name: barbican log dir
  file: dest=/var/log/barbican state=directory mode=2750 owner=barbican
        group=adm

- name: Change barbican log dir acl
  acl: name=/var/log/barbican state=present default=yes etype={{ item.etype }} permissions={{ item.permission }}
  with_items:
    - etype: user
      permission: rw
    - etype: group
      permission: r
    - etype: other
      permission: r
