---
testenv_instance_names:
  - "{{ testenv_instance_prefix }}-controller-0"
  - "{{ testenv_instance_prefix }}-controller-1"
  - "{{ testenv_instance_prefix }}-compute-0"
testenv_keypair_name: int-test
testenv_keypair_path: "{{ ansible_env.ROOT }}/envs/test/{{ testenv_keypair_name }}.pem"
testenv_image_id: "{{ ansible_env.IMAGE_ID }}"
testenv_security_groups_description: Rules for testing
testenv_security_groups: "{{ testenv_instance_prefix }}_ursula"
testenv_security_group_rules:
  - { proto: 'tcp', port: 22, state: 'present' }     # SSH (Ansible)
  - { proto: 'tcp', port: 80, state: 'present' }     # HTTPS redirect
  - { proto: 'tcp', port: 443, state: 'present' }    # Horizon SSL
  - { proto: 'tcp', port: 5001, state: 'present' }   # Keystone SSL
  - { proto: 'tcp', port: 6080, state: 'present' }   # NoVNC proxy
  - { proto: 'tcp', port: 8777, state: 'present' }   # Nova SSL
  - { proto: 'tcp', port: 8778, state: 'present' }   # Cinder SSL
  - { proto: 'tcp', port: 9292, state: 'present' }   # Glance
  - { proto: 'tcp', port: 9393, state: 'present' }   # Glance SSL
  - { proto: 'tcp', port: 9797, state: 'present' }   # Neutron SSL
  - { proto: 'tcp', port: 9798, state: 'present' }   # Cinder SSL
  - { proto: 'icmp', port: -1, state: 'present' }
testenv_security_groups_cleanup: True
